source 'http://rubygems.org'

gem 'rails', '3.1.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails', '~> 3.1.1'
  gem 'sass-rails',   '~> 3.1.4'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'crummy', path: '../'
gem 'haml'

group :test do
  # Pretty printed test output
  gem 'turn', require: false
end

group :test, :development do
  gem 'rspec-rails', '~> 2.0'
end
